#############################################################################
# Makefile for building: build/tc
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  tiger-compiler.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile tiger-compiler.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe $(shell llvm-config-10 --cxxflags) -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/lib/llvm-10/include -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = tc1.0.0
DISTDIR = /home/maicon/work/uem/compiladores/tiger-compiler/build/tc1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) $(shell llvm-config-10 --ldflags --system-libs --libs all) -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main.cpp \
		src/ast/ast.cpp \
		src/codegen/codegen.cpp \
		src/utils/codegencontext.cpp \
		src/utils/symboltable.cpp src/tiger.lexer.cpp \
		src/tiger.parser.cpp
OBJECTS       = build/main.o \
		build/ast.o \
		build/codegen.o \
		build/codegencontext.o \
		build/symboltable.o \
		build/tiger.lexer.o \
		build/tiger.parser.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		tiger-compiler.pro src/ast/ast.hpp \
		src/utils/codegencontext.hpp \
		src/utils/symboltable.hpp src/main.cpp \
		src/ast/ast.cpp \
		src/codegen/codegen.cpp \
		src/utils/codegencontext.cpp \
		src/utils/symboltable.cpp
QMAKE_TARGET  = tc
DESTDIR       = build/
TARGET        = build/tc


first: all
####### Build rules

build/tc: src/tiger.lexer.cpp src/tiger.parser.cpp src/tiger.parser.hpp $(OBJECTS)  
	@test -d build/ || mkdir -p build/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tiger-compiler.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		tiger-compiler.pro
	$(QMAKE) -o Makefile tiger-compiler.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
tiger-compiler.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile tiger-compiler.pro

qmake_all: FORCE


all: Makefile build/tc

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/tiger.l $(DISTDIR)/
	$(COPY_FILE) --parents src/tiger.y $(DISTDIR)/
	$(COPY_FILE) --parents src/tiger.y $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_flex_make_all: src/tiger.lexer.cpp
compiler_flex_clean:
	-$(DEL_FILE) src/tiger.lexer.cpp
src/tiger.lexer.cpp: src/tiger.l
	flex -o src/tiger.lexer.cpp src/tiger.l

compiler_bison_make_all: src/tiger.parser.cpp
compiler_bison_clean:
	-$(DEL_FILE) src/tiger.parser.cpp
src/tiger.parser.cpp: src/tiger.y
	bison -dv -o src/tiger.parser.cpp src/tiger.y

compiler_bison_header_make_all: src/tiger.parser.hpp
compiler_bison_header_clean:
	-$(DEL_FILE) src/tiger.parser.hpp
src/tiger.parser.hpp: src/tiger.y
	bison -dv -o src/tiger.parser.cpp src/tiger.y

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_flex_clean compiler_bison_clean compiler_bison_header_clean 

####### Compile

build/main.o: src/main.cpp src/ast/ast.hpp \
		/usr/lib/llvm-10/include/llvm/IR/Function.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseSet.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseMap.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseMapInfo.h \
		/usr/lib/llvm-10/include/llvm/ADT/ArrayRef.h \
		/usr/lib/llvm-10/include/llvm/ADT/Hashing.h \
		/usr/lib/llvm-10/include/llvm/Support/DataTypes.h \
		/usr/lib/llvm-10/include/llvm-c/DataTypes.h \
		/usr/lib/llvm-10/include/llvm/Support/ErrorHandling.h \
		/usr/lib/llvm-10/include/llvm/Support/Compiler.h \
		/usr/lib/llvm-10/include/llvm/Config/llvm-config.h \
		/usr/lib/llvm-10/include/llvm/Support/SwapByteOrder.h \
		/usr/lib/llvm-10/include/llvm/Support/type_traits.h \
		/usr/lib/llvm-10/include/llvm/ADT/None.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallVector.h \
		/usr/lib/llvm-10/include/llvm/ADT/iterator_range.h \
		/usr/lib/llvm-10/include/llvm/Support/AlignOf.h \
		/usr/lib/llvm-10/include/llvm/Support/MathExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/MemAlloc.h \
		/usr/lib/llvm-10/include/llvm/ADT/STLExtras.h \
		/usr/lib/llvm-10/include/llvm/ADT/Optional.h \
		/usr/lib/llvm-10/include/llvm/ADT/iterator.h \
		/usr/lib/llvm-10/include/llvm/Config/abi-breaking.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringRef.h \
		/usr/lib/llvm-10/include/llvm/Support/PointerLikeTypeTraits.h \
		/usr/lib/llvm-10/include/llvm/Support/TypeSize.h \
		/usr/lib/llvm-10/include/llvm/ADT/EpochTracker.h \
		/usr/lib/llvm-10/include/llvm/Support/ReverseIteration.h \
		/usr/lib/llvm-10/include/llvm/ADT/Twine.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node_base.h \
		/usr/lib/llvm-10/include/llvm/ADT/PointerIntPair.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node_options.h \
		/usr/lib/llvm-10/include/llvm/IR/Argument.h \
		/usr/lib/llvm-10/include/llvm/IR/Attributes.h \
		/usr/lib/llvm-10/include/llvm-c/Types.h \
		/usr/lib/llvm-10/include/llvm-c/ExternC.h \
		/usr/lib/llvm-10/include/llvm/ADT/FoldingSet.h \
		/usr/lib/llvm-10/include/llvm/Support/Allocator.h \
		/usr/lib/llvm-10/include/llvm/Support/Alignment.h \
		/usr/lib/llvm-10/include/llvm/IR/Attributes.inc \
		/usr/lib/llvm-10/include/llvm/IR/Value.h \
		/usr/lib/llvm-10/include/llvm/IR/Use.h \
		/usr/lib/llvm-10/include/llvm/Support/CBindingWrapping.h \
		/usr/lib/llvm-10/include/llvm/Support/Casting.h \
		/usr/lib/llvm-10/include/llvm/IR/Value.def \
		/usr/lib/llvm-10/include/llvm/IR/BasicBlock.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist.h \
		/usr/lib/llvm-10/include/llvm/ADT/simple_ilist.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_base.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_iterator.h \
		/usr/lib/llvm-10/include/llvm/IR/Instruction.h \
		/usr/lib/llvm-10/include/llvm/IR/DebugLoc.h \
		/usr/lib/llvm-10/include/llvm/IR/TrackingMDRef.h \
		/usr/lib/llvm-10/include/llvm/IR/Metadata.h \
		/usr/lib/llvm-10/include/llvm/ADT/PointerUnion.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringMap.h \
		/usr/lib/llvm-10/include/llvm/IR/Constant.h \
		/usr/lib/llvm-10/include/llvm/IR/User.h \
		/usr/lib/llvm-10/include/llvm/IR/LLVMContext.h \
		/usr/lib/llvm-10/include/llvm/IR/DiagnosticHandler.h \
		/usr/lib/llvm-10/include/llvm/IR/FixedMetadataKinds.def \
		/usr/lib/llvm-10/include/llvm/IR/Metadata.def \
		/usr/lib/llvm-10/include/llvm/IR/SymbolTableListTraits.h \
		/usr/lib/llvm-10/include/llvm/IR/Instruction.def \
		/usr/lib/llvm-10/include/llvm/IR/CallingConv.h \
		/usr/lib/llvm-10/include/llvm/IR/DerivedTypes.h \
		/usr/lib/llvm-10/include/llvm/IR/Type.h \
		/usr/lib/llvm-10/include/llvm/ADT/APFloat.h \
		/usr/lib/llvm-10/include/llvm/ADT/APInt.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallPtrSet.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalObject.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalValue.h \
		/usr/lib/llvm-10/include/llvm/Support/MD5.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallString.h \
		/usr/lib/llvm-10/include/llvm/Support/Endian.h \
		/usr/lib/llvm-10/include/llvm/Support/Host.h \
		/usr/lib/llvm-10/include/llvm/IR/OperandTraits.h \
		src/utils/codegencontext.hpp \
		/usr/lib/llvm-10/include/llvm/IR/IRBuilder.h \
		/usr/lib/llvm-10/include/llvm/IR/ConstantFolder.h \
		/usr/lib/llvm-10/include/llvm/IR/Constants.h \
		/usr/lib/llvm-10/include/llvm/IR/InstrTypes.h \
		/usr/lib/llvm-10/include/llvm/IR/DataLayout.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalVariable.h \
		/usr/lib/llvm-10/include/llvm/IR/Instructions.h \
		/usr/lib/llvm-10/include/llvm/Support/AtomicOrdering.h \
		/usr/lib/llvm-10/include/llvm/IR/IntrinsicInst.h \
		/usr/lib/llvm-10/include/llvm/IR/FPEnv.h \
		/usr/lib/llvm-10/include/llvm/IR/Intrinsics.h \
		/usr/lib/llvm-10/include/llvm/IR/IntrinsicEnums.inc \
		/usr/lib/llvm-10/include/llvm/IR/Module.h \
		/usr/lib/llvm-10/include/llvm/IR/Comdat.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalAlias.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalIndirectSymbol.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalIFunc.h \
		/usr/lib/llvm-10/include/llvm/IR/ProfileSummary.h \
		/usr/lib/llvm-10/include/llvm/Support/CodeGen.h \
		/usr/lib/llvm-10/include/llvm/IR/Operator.h \
		/usr/lib/llvm-10/include/llvm/IR/ValueHandle.h \
		/usr/lib/llvm-10/include/llvm/IR/ConstrainedOps.def \
		/usr/lib/llvm-10/include/llvm/IR/IRPrintingPasses.h \
		/usr/lib/llvm-10/include/llvm/IR/LegacyPassManager.h \
		/usr/lib/llvm-10/include/llvm/Pass.h \
		/usr/lib/llvm-10/include/llvm/PassAnalysisSupport.h \
		/usr/lib/llvm-10/include/llvm/PassSupport.h \
		/usr/lib/llvm-10/include/llvm/PassInfo.h \
		/usr/lib/llvm-10/include/llvm/PassRegistry.h \
		/usr/lib/llvm-10/include/llvm/Support/RWMutex.h \
		/usr/lib/llvm-10/include/llvm/Support/Threading.h \
		/usr/lib/llvm-10/include/llvm/ADT/FunctionExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/Atomic.h \
		/usr/lib/llvm-10/include/llvm/IR/Verifier.h \
		/usr/lib/llvm-10/include/llvm/IR/PassManager.h \
		/usr/lib/llvm-10/include/llvm/ADT/TinyPtrVector.h \
		/usr/lib/llvm-10/include/llvm/IR/PassInstrumentation.h \
		/usr/lib/llvm-10/include/llvm/ADT/Any.h \
		/usr/lib/llvm-10/include/llvm/Support/TypeName.h \
		/usr/lib/llvm-10/include/llvm/IR/PassManagerInternal.h \
		/usr/lib/llvm-10/include/llvm/Support/Debug.h \
		/usr/lib/llvm-10/include/llvm/Support/raw_ostream.h \
		/usr/lib/llvm-10/include/llvm/Support/FileSystem.h \
		/usr/lib/llvm-10/include/llvm/Support/Chrono.h \
		/usr/lib/llvm-10/include/llvm/Support/FormatProviders.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringSwitch.h \
		/usr/lib/llvm-10/include/llvm/Support/FormatVariadicDetails.h \
		/usr/lib/llvm-10/include/llvm/Support/NativeFormatting.h \
		/usr/lib/llvm-10/include/llvm/Support/Error.h \
		/usr/lib/llvm-10/include/llvm-c/Error.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/ErrorOr.h \
		/usr/lib/llvm-10/include/llvm/Support/Format.h \
		/usr/lib/llvm-10/include/llvm/Support/TargetRegistry.h \
		/usr/lib/llvm-10/include/llvm-c/DisassemblerTypes.h \
		/usr/lib/llvm-10/include/llvm/ADT/Triple.h \
		/usr/lib/llvm-10/include/llvm/Support/FormattedStream.h \
		/usr/lib/llvm-10/include/llvm/Support/TargetSelect.h \
		/usr/lib/llvm-10/include/llvm/Config/Targets.def \
		/usr/lib/llvm-10/include/llvm/Config/AsmPrinters.def \
		/usr/lib/llvm-10/include/llvm/Config/AsmParsers.def \
		/usr/lib/llvm-10/include/llvm/Config/Disassemblers.def \
		/usr/lib/llvm-10/include/llvm/Target/TargetMachine.h \
		/usr/lib/llvm-10/include/llvm/Target/TargetOptions.h \
		/usr/lib/llvm-10/include/llvm/MC/MCTargetOptions.h \
		src/utils/symboltable.hpp \
		src/tiger.parser.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/ast.o: src/ast/ast.cpp src/ast/ast.hpp \
		/usr/lib/llvm-10/include/llvm/IR/Function.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseSet.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseMap.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseMapInfo.h \
		/usr/lib/llvm-10/include/llvm/ADT/ArrayRef.h \
		/usr/lib/llvm-10/include/llvm/ADT/Hashing.h \
		/usr/lib/llvm-10/include/llvm/Support/DataTypes.h \
		/usr/lib/llvm-10/include/llvm-c/DataTypes.h \
		/usr/lib/llvm-10/include/llvm/Support/ErrorHandling.h \
		/usr/lib/llvm-10/include/llvm/Support/Compiler.h \
		/usr/lib/llvm-10/include/llvm/Config/llvm-config.h \
		/usr/lib/llvm-10/include/llvm/Support/SwapByteOrder.h \
		/usr/lib/llvm-10/include/llvm/Support/type_traits.h \
		/usr/lib/llvm-10/include/llvm/ADT/None.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallVector.h \
		/usr/lib/llvm-10/include/llvm/ADT/iterator_range.h \
		/usr/lib/llvm-10/include/llvm/Support/AlignOf.h \
		/usr/lib/llvm-10/include/llvm/Support/MathExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/MemAlloc.h \
		/usr/lib/llvm-10/include/llvm/ADT/STLExtras.h \
		/usr/lib/llvm-10/include/llvm/ADT/Optional.h \
		/usr/lib/llvm-10/include/llvm/ADT/iterator.h \
		/usr/lib/llvm-10/include/llvm/Config/abi-breaking.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringRef.h \
		/usr/lib/llvm-10/include/llvm/Support/PointerLikeTypeTraits.h \
		/usr/lib/llvm-10/include/llvm/Support/TypeSize.h \
		/usr/lib/llvm-10/include/llvm/ADT/EpochTracker.h \
		/usr/lib/llvm-10/include/llvm/Support/ReverseIteration.h \
		/usr/lib/llvm-10/include/llvm/ADT/Twine.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node_base.h \
		/usr/lib/llvm-10/include/llvm/ADT/PointerIntPair.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node_options.h \
		/usr/lib/llvm-10/include/llvm/IR/Argument.h \
		/usr/lib/llvm-10/include/llvm/IR/Attributes.h \
		/usr/lib/llvm-10/include/llvm-c/Types.h \
		/usr/lib/llvm-10/include/llvm-c/ExternC.h \
		/usr/lib/llvm-10/include/llvm/ADT/FoldingSet.h \
		/usr/lib/llvm-10/include/llvm/Support/Allocator.h \
		/usr/lib/llvm-10/include/llvm/Support/Alignment.h \
		/usr/lib/llvm-10/include/llvm/IR/Attributes.inc \
		/usr/lib/llvm-10/include/llvm/IR/Value.h \
		/usr/lib/llvm-10/include/llvm/IR/Use.h \
		/usr/lib/llvm-10/include/llvm/Support/CBindingWrapping.h \
		/usr/lib/llvm-10/include/llvm/Support/Casting.h \
		/usr/lib/llvm-10/include/llvm/IR/Value.def \
		/usr/lib/llvm-10/include/llvm/IR/BasicBlock.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist.h \
		/usr/lib/llvm-10/include/llvm/ADT/simple_ilist.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_base.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_iterator.h \
		/usr/lib/llvm-10/include/llvm/IR/Instruction.h \
		/usr/lib/llvm-10/include/llvm/IR/DebugLoc.h \
		/usr/lib/llvm-10/include/llvm/IR/TrackingMDRef.h \
		/usr/lib/llvm-10/include/llvm/IR/Metadata.h \
		/usr/lib/llvm-10/include/llvm/ADT/PointerUnion.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringMap.h \
		/usr/lib/llvm-10/include/llvm/IR/Constant.h \
		/usr/lib/llvm-10/include/llvm/IR/User.h \
		/usr/lib/llvm-10/include/llvm/IR/LLVMContext.h \
		/usr/lib/llvm-10/include/llvm/IR/DiagnosticHandler.h \
		/usr/lib/llvm-10/include/llvm/IR/FixedMetadataKinds.def \
		/usr/lib/llvm-10/include/llvm/IR/Metadata.def \
		/usr/lib/llvm-10/include/llvm/IR/SymbolTableListTraits.h \
		/usr/lib/llvm-10/include/llvm/IR/Instruction.def \
		/usr/lib/llvm-10/include/llvm/IR/CallingConv.h \
		/usr/lib/llvm-10/include/llvm/IR/DerivedTypes.h \
		/usr/lib/llvm-10/include/llvm/IR/Type.h \
		/usr/lib/llvm-10/include/llvm/ADT/APFloat.h \
		/usr/lib/llvm-10/include/llvm/ADT/APInt.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallPtrSet.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalObject.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalValue.h \
		/usr/lib/llvm-10/include/llvm/Support/MD5.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallString.h \
		/usr/lib/llvm-10/include/llvm/Support/Endian.h \
		/usr/lib/llvm-10/include/llvm/Support/Host.h \
		/usr/lib/llvm-10/include/llvm/IR/OperandTraits.h \
		src/utils/codegencontext.hpp \
		/usr/lib/llvm-10/include/llvm/IR/IRBuilder.h \
		/usr/lib/llvm-10/include/llvm/IR/ConstantFolder.h \
		/usr/lib/llvm-10/include/llvm/IR/Constants.h \
		/usr/lib/llvm-10/include/llvm/IR/InstrTypes.h \
		/usr/lib/llvm-10/include/llvm/IR/DataLayout.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalVariable.h \
		/usr/lib/llvm-10/include/llvm/IR/Instructions.h \
		/usr/lib/llvm-10/include/llvm/Support/AtomicOrdering.h \
		/usr/lib/llvm-10/include/llvm/IR/IntrinsicInst.h \
		/usr/lib/llvm-10/include/llvm/IR/FPEnv.h \
		/usr/lib/llvm-10/include/llvm/IR/Intrinsics.h \
		/usr/lib/llvm-10/include/llvm/IR/IntrinsicEnums.inc \
		/usr/lib/llvm-10/include/llvm/IR/Module.h \
		/usr/lib/llvm-10/include/llvm/IR/Comdat.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalAlias.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalIndirectSymbol.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalIFunc.h \
		/usr/lib/llvm-10/include/llvm/IR/ProfileSummary.h \
		/usr/lib/llvm-10/include/llvm/Support/CodeGen.h \
		/usr/lib/llvm-10/include/llvm/IR/Operator.h \
		/usr/lib/llvm-10/include/llvm/IR/ValueHandle.h \
		/usr/lib/llvm-10/include/llvm/IR/ConstrainedOps.def \
		/usr/lib/llvm-10/include/llvm/IR/IRPrintingPasses.h \
		/usr/lib/llvm-10/include/llvm/IR/LegacyPassManager.h \
		/usr/lib/llvm-10/include/llvm/Pass.h \
		/usr/lib/llvm-10/include/llvm/PassAnalysisSupport.h \
		/usr/lib/llvm-10/include/llvm/PassSupport.h \
		/usr/lib/llvm-10/include/llvm/PassInfo.h \
		/usr/lib/llvm-10/include/llvm/PassRegistry.h \
		/usr/lib/llvm-10/include/llvm/Support/RWMutex.h \
		/usr/lib/llvm-10/include/llvm/Support/Threading.h \
		/usr/lib/llvm-10/include/llvm/ADT/FunctionExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/Atomic.h \
		/usr/lib/llvm-10/include/llvm/IR/Verifier.h \
		/usr/lib/llvm-10/include/llvm/IR/PassManager.h \
		/usr/lib/llvm-10/include/llvm/ADT/TinyPtrVector.h \
		/usr/lib/llvm-10/include/llvm/IR/PassInstrumentation.h \
		/usr/lib/llvm-10/include/llvm/ADT/Any.h \
		/usr/lib/llvm-10/include/llvm/Support/TypeName.h \
		/usr/lib/llvm-10/include/llvm/IR/PassManagerInternal.h \
		/usr/lib/llvm-10/include/llvm/Support/Debug.h \
		/usr/lib/llvm-10/include/llvm/Support/raw_ostream.h \
		/usr/lib/llvm-10/include/llvm/Support/FileSystem.h \
		/usr/lib/llvm-10/include/llvm/Support/Chrono.h \
		/usr/lib/llvm-10/include/llvm/Support/FormatProviders.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringSwitch.h \
		/usr/lib/llvm-10/include/llvm/Support/FormatVariadicDetails.h \
		/usr/lib/llvm-10/include/llvm/Support/NativeFormatting.h \
		/usr/lib/llvm-10/include/llvm/Support/Error.h \
		/usr/lib/llvm-10/include/llvm-c/Error.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/ErrorOr.h \
		/usr/lib/llvm-10/include/llvm/Support/Format.h \
		/usr/lib/llvm-10/include/llvm/Support/TargetRegistry.h \
		/usr/lib/llvm-10/include/llvm-c/DisassemblerTypes.h \
		/usr/lib/llvm-10/include/llvm/ADT/Triple.h \
		/usr/lib/llvm-10/include/llvm/Support/FormattedStream.h \
		/usr/lib/llvm-10/include/llvm/Support/TargetSelect.h \
		/usr/lib/llvm-10/include/llvm/Config/Targets.def \
		/usr/lib/llvm-10/include/llvm/Config/AsmPrinters.def \
		/usr/lib/llvm-10/include/llvm/Config/AsmParsers.def \
		/usr/lib/llvm-10/include/llvm/Config/Disassemblers.def \
		/usr/lib/llvm-10/include/llvm/Target/TargetMachine.h \
		/usr/lib/llvm-10/include/llvm/Target/TargetOptions.h \
		/usr/lib/llvm-10/include/llvm/MC/MCTargetOptions.h \
		src/utils/symboltable.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ast.o src/ast/ast.cpp

build/codegen.o: src/codegen/codegen.cpp src/utils/codegencontext.hpp \
		src/ast/ast.hpp \
		/usr/lib/llvm-10/include/llvm/IR/Function.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseSet.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseMap.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseMapInfo.h \
		/usr/lib/llvm-10/include/llvm/ADT/ArrayRef.h \
		/usr/lib/llvm-10/include/llvm/ADT/Hashing.h \
		/usr/lib/llvm-10/include/llvm/Support/DataTypes.h \
		/usr/lib/llvm-10/include/llvm-c/DataTypes.h \
		/usr/lib/llvm-10/include/llvm/Support/ErrorHandling.h \
		/usr/lib/llvm-10/include/llvm/Support/Compiler.h \
		/usr/lib/llvm-10/include/llvm/Config/llvm-config.h \
		/usr/lib/llvm-10/include/llvm/Support/SwapByteOrder.h \
		/usr/lib/llvm-10/include/llvm/Support/type_traits.h \
		/usr/lib/llvm-10/include/llvm/ADT/None.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallVector.h \
		/usr/lib/llvm-10/include/llvm/ADT/iterator_range.h \
		/usr/lib/llvm-10/include/llvm/Support/AlignOf.h \
		/usr/lib/llvm-10/include/llvm/Support/MathExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/MemAlloc.h \
		/usr/lib/llvm-10/include/llvm/ADT/STLExtras.h \
		/usr/lib/llvm-10/include/llvm/ADT/Optional.h \
		/usr/lib/llvm-10/include/llvm/ADT/iterator.h \
		/usr/lib/llvm-10/include/llvm/Config/abi-breaking.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringRef.h \
		/usr/lib/llvm-10/include/llvm/Support/PointerLikeTypeTraits.h \
		/usr/lib/llvm-10/include/llvm/Support/TypeSize.h \
		/usr/lib/llvm-10/include/llvm/ADT/EpochTracker.h \
		/usr/lib/llvm-10/include/llvm/Support/ReverseIteration.h \
		/usr/lib/llvm-10/include/llvm/ADT/Twine.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node_base.h \
		/usr/lib/llvm-10/include/llvm/ADT/PointerIntPair.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node_options.h \
		/usr/lib/llvm-10/include/llvm/IR/Argument.h \
		/usr/lib/llvm-10/include/llvm/IR/Attributes.h \
		/usr/lib/llvm-10/include/llvm-c/Types.h \
		/usr/lib/llvm-10/include/llvm-c/ExternC.h \
		/usr/lib/llvm-10/include/llvm/ADT/FoldingSet.h \
		/usr/lib/llvm-10/include/llvm/Support/Allocator.h \
		/usr/lib/llvm-10/include/llvm/Support/Alignment.h \
		/usr/lib/llvm-10/include/llvm/IR/Attributes.inc \
		/usr/lib/llvm-10/include/llvm/IR/Value.h \
		/usr/lib/llvm-10/include/llvm/IR/Use.h \
		/usr/lib/llvm-10/include/llvm/Support/CBindingWrapping.h \
		/usr/lib/llvm-10/include/llvm/Support/Casting.h \
		/usr/lib/llvm-10/include/llvm/IR/Value.def \
		/usr/lib/llvm-10/include/llvm/IR/BasicBlock.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist.h \
		/usr/lib/llvm-10/include/llvm/ADT/simple_ilist.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_base.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_iterator.h \
		/usr/lib/llvm-10/include/llvm/IR/Instruction.h \
		/usr/lib/llvm-10/include/llvm/IR/DebugLoc.h \
		/usr/lib/llvm-10/include/llvm/IR/TrackingMDRef.h \
		/usr/lib/llvm-10/include/llvm/IR/Metadata.h \
		/usr/lib/llvm-10/include/llvm/ADT/PointerUnion.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringMap.h \
		/usr/lib/llvm-10/include/llvm/IR/Constant.h \
		/usr/lib/llvm-10/include/llvm/IR/User.h \
		/usr/lib/llvm-10/include/llvm/IR/LLVMContext.h \
		/usr/lib/llvm-10/include/llvm/IR/DiagnosticHandler.h \
		/usr/lib/llvm-10/include/llvm/IR/FixedMetadataKinds.def \
		/usr/lib/llvm-10/include/llvm/IR/Metadata.def \
		/usr/lib/llvm-10/include/llvm/IR/SymbolTableListTraits.h \
		/usr/lib/llvm-10/include/llvm/IR/Instruction.def \
		/usr/lib/llvm-10/include/llvm/IR/CallingConv.h \
		/usr/lib/llvm-10/include/llvm/IR/DerivedTypes.h \
		/usr/lib/llvm-10/include/llvm/IR/Type.h \
		/usr/lib/llvm-10/include/llvm/ADT/APFloat.h \
		/usr/lib/llvm-10/include/llvm/ADT/APInt.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallPtrSet.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalObject.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalValue.h \
		/usr/lib/llvm-10/include/llvm/Support/MD5.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallString.h \
		/usr/lib/llvm-10/include/llvm/Support/Endian.h \
		/usr/lib/llvm-10/include/llvm/Support/Host.h \
		/usr/lib/llvm-10/include/llvm/IR/OperandTraits.h \
		/usr/lib/llvm-10/include/llvm/IR/IRBuilder.h \
		/usr/lib/llvm-10/include/llvm/IR/ConstantFolder.h \
		/usr/lib/llvm-10/include/llvm/IR/Constants.h \
		/usr/lib/llvm-10/include/llvm/IR/InstrTypes.h \
		/usr/lib/llvm-10/include/llvm/IR/DataLayout.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalVariable.h \
		/usr/lib/llvm-10/include/llvm/IR/Instructions.h \
		/usr/lib/llvm-10/include/llvm/Support/AtomicOrdering.h \
		/usr/lib/llvm-10/include/llvm/IR/IntrinsicInst.h \
		/usr/lib/llvm-10/include/llvm/IR/FPEnv.h \
		/usr/lib/llvm-10/include/llvm/IR/Intrinsics.h \
		/usr/lib/llvm-10/include/llvm/IR/IntrinsicEnums.inc \
		/usr/lib/llvm-10/include/llvm/IR/Module.h \
		/usr/lib/llvm-10/include/llvm/IR/Comdat.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalAlias.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalIndirectSymbol.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalIFunc.h \
		/usr/lib/llvm-10/include/llvm/IR/ProfileSummary.h \
		/usr/lib/llvm-10/include/llvm/Support/CodeGen.h \
		/usr/lib/llvm-10/include/llvm/IR/Operator.h \
		/usr/lib/llvm-10/include/llvm/IR/ValueHandle.h \
		/usr/lib/llvm-10/include/llvm/IR/ConstrainedOps.def \
		/usr/lib/llvm-10/include/llvm/IR/IRPrintingPasses.h \
		/usr/lib/llvm-10/include/llvm/IR/LegacyPassManager.h \
		/usr/lib/llvm-10/include/llvm/Pass.h \
		/usr/lib/llvm-10/include/llvm/PassAnalysisSupport.h \
		/usr/lib/llvm-10/include/llvm/PassSupport.h \
		/usr/lib/llvm-10/include/llvm/PassInfo.h \
		/usr/lib/llvm-10/include/llvm/PassRegistry.h \
		/usr/lib/llvm-10/include/llvm/Support/RWMutex.h \
		/usr/lib/llvm-10/include/llvm/Support/Threading.h \
		/usr/lib/llvm-10/include/llvm/ADT/FunctionExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/Atomic.h \
		/usr/lib/llvm-10/include/llvm/IR/Verifier.h \
		/usr/lib/llvm-10/include/llvm/IR/PassManager.h \
		/usr/lib/llvm-10/include/llvm/ADT/TinyPtrVector.h \
		/usr/lib/llvm-10/include/llvm/IR/PassInstrumentation.h \
		/usr/lib/llvm-10/include/llvm/ADT/Any.h \
		/usr/lib/llvm-10/include/llvm/Support/TypeName.h \
		/usr/lib/llvm-10/include/llvm/IR/PassManagerInternal.h \
		/usr/lib/llvm-10/include/llvm/Support/Debug.h \
		/usr/lib/llvm-10/include/llvm/Support/raw_ostream.h \
		/usr/lib/llvm-10/include/llvm/Support/FileSystem.h \
		/usr/lib/llvm-10/include/llvm/Support/Chrono.h \
		/usr/lib/llvm-10/include/llvm/Support/FormatProviders.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringSwitch.h \
		/usr/lib/llvm-10/include/llvm/Support/FormatVariadicDetails.h \
		/usr/lib/llvm-10/include/llvm/Support/NativeFormatting.h \
		/usr/lib/llvm-10/include/llvm/Support/Error.h \
		/usr/lib/llvm-10/include/llvm-c/Error.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/ErrorOr.h \
		/usr/lib/llvm-10/include/llvm/Support/Format.h \
		/usr/lib/llvm-10/include/llvm/Support/TargetRegistry.h \
		/usr/lib/llvm-10/include/llvm-c/DisassemblerTypes.h \
		/usr/lib/llvm-10/include/llvm/ADT/Triple.h \
		/usr/lib/llvm-10/include/llvm/Support/FormattedStream.h \
		/usr/lib/llvm-10/include/llvm/Support/TargetSelect.h \
		/usr/lib/llvm-10/include/llvm/Config/Targets.def \
		/usr/lib/llvm-10/include/llvm/Config/AsmPrinters.def \
		/usr/lib/llvm-10/include/llvm/Config/AsmParsers.def \
		/usr/lib/llvm-10/include/llvm/Config/Disassemblers.def \
		/usr/lib/llvm-10/include/llvm/Target/TargetMachine.h \
		/usr/lib/llvm-10/include/llvm/Target/TargetOptions.h \
		/usr/lib/llvm-10/include/llvm/MC/MCTargetOptions.h \
		src/utils/symboltable.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/codegen.o src/codegen/codegen.cpp

build/codegencontext.o: src/utils/codegencontext.cpp src/utils/codegencontext.hpp \
		src/ast/ast.hpp \
		/usr/lib/llvm-10/include/llvm/IR/Function.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseSet.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseMap.h \
		/usr/lib/llvm-10/include/llvm/ADT/DenseMapInfo.h \
		/usr/lib/llvm-10/include/llvm/ADT/ArrayRef.h \
		/usr/lib/llvm-10/include/llvm/ADT/Hashing.h \
		/usr/lib/llvm-10/include/llvm/Support/DataTypes.h \
		/usr/lib/llvm-10/include/llvm-c/DataTypes.h \
		/usr/lib/llvm-10/include/llvm/Support/ErrorHandling.h \
		/usr/lib/llvm-10/include/llvm/Support/Compiler.h \
		/usr/lib/llvm-10/include/llvm/Config/llvm-config.h \
		/usr/lib/llvm-10/include/llvm/Support/SwapByteOrder.h \
		/usr/lib/llvm-10/include/llvm/Support/type_traits.h \
		/usr/lib/llvm-10/include/llvm/ADT/None.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallVector.h \
		/usr/lib/llvm-10/include/llvm/ADT/iterator_range.h \
		/usr/lib/llvm-10/include/llvm/Support/AlignOf.h \
		/usr/lib/llvm-10/include/llvm/Support/MathExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/MemAlloc.h \
		/usr/lib/llvm-10/include/llvm/ADT/STLExtras.h \
		/usr/lib/llvm-10/include/llvm/ADT/Optional.h \
		/usr/lib/llvm-10/include/llvm/ADT/iterator.h \
		/usr/lib/llvm-10/include/llvm/Config/abi-breaking.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringRef.h \
		/usr/lib/llvm-10/include/llvm/Support/PointerLikeTypeTraits.h \
		/usr/lib/llvm-10/include/llvm/Support/TypeSize.h \
		/usr/lib/llvm-10/include/llvm/ADT/EpochTracker.h \
		/usr/lib/llvm-10/include/llvm/Support/ReverseIteration.h \
		/usr/lib/llvm-10/include/llvm/ADT/Twine.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node_base.h \
		/usr/lib/llvm-10/include/llvm/ADT/PointerIntPair.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_node_options.h \
		/usr/lib/llvm-10/include/llvm/IR/Argument.h \
		/usr/lib/llvm-10/include/llvm/IR/Attributes.h \
		/usr/lib/llvm-10/include/llvm-c/Types.h \
		/usr/lib/llvm-10/include/llvm-c/ExternC.h \
		/usr/lib/llvm-10/include/llvm/ADT/FoldingSet.h \
		/usr/lib/llvm-10/include/llvm/Support/Allocator.h \
		/usr/lib/llvm-10/include/llvm/Support/Alignment.h \
		/usr/lib/llvm-10/include/llvm/IR/Attributes.inc \
		/usr/lib/llvm-10/include/llvm/IR/Value.h \
		/usr/lib/llvm-10/include/llvm/IR/Use.h \
		/usr/lib/llvm-10/include/llvm/Support/CBindingWrapping.h \
		/usr/lib/llvm-10/include/llvm/Support/Casting.h \
		/usr/lib/llvm-10/include/llvm/IR/Value.def \
		/usr/lib/llvm-10/include/llvm/IR/BasicBlock.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist.h \
		/usr/lib/llvm-10/include/llvm/ADT/simple_ilist.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_base.h \
		/usr/lib/llvm-10/include/llvm/ADT/ilist_iterator.h \
		/usr/lib/llvm-10/include/llvm/IR/Instruction.h \
		/usr/lib/llvm-10/include/llvm/IR/DebugLoc.h \
		/usr/lib/llvm-10/include/llvm/IR/TrackingMDRef.h \
		/usr/lib/llvm-10/include/llvm/IR/Metadata.h \
		/usr/lib/llvm-10/include/llvm/ADT/PointerUnion.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringMap.h \
		/usr/lib/llvm-10/include/llvm/IR/Constant.h \
		/usr/lib/llvm-10/include/llvm/IR/User.h \
		/usr/lib/llvm-10/include/llvm/IR/LLVMContext.h \
		/usr/lib/llvm-10/include/llvm/IR/DiagnosticHandler.h \
		/usr/lib/llvm-10/include/llvm/IR/FixedMetadataKinds.def \
		/usr/lib/llvm-10/include/llvm/IR/Metadata.def \
		/usr/lib/llvm-10/include/llvm/IR/SymbolTableListTraits.h \
		/usr/lib/llvm-10/include/llvm/IR/Instruction.def \
		/usr/lib/llvm-10/include/llvm/IR/CallingConv.h \
		/usr/lib/llvm-10/include/llvm/IR/DerivedTypes.h \
		/usr/lib/llvm-10/include/llvm/IR/Type.h \
		/usr/lib/llvm-10/include/llvm/ADT/APFloat.h \
		/usr/lib/llvm-10/include/llvm/ADT/APInt.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallPtrSet.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalObject.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalValue.h \
		/usr/lib/llvm-10/include/llvm/Support/MD5.h \
		/usr/lib/llvm-10/include/llvm/ADT/SmallString.h \
		/usr/lib/llvm-10/include/llvm/Support/Endian.h \
		/usr/lib/llvm-10/include/llvm/Support/Host.h \
		/usr/lib/llvm-10/include/llvm/IR/OperandTraits.h \
		/usr/lib/llvm-10/include/llvm/IR/IRBuilder.h \
		/usr/lib/llvm-10/include/llvm/IR/ConstantFolder.h \
		/usr/lib/llvm-10/include/llvm/IR/Constants.h \
		/usr/lib/llvm-10/include/llvm/IR/InstrTypes.h \
		/usr/lib/llvm-10/include/llvm/IR/DataLayout.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalVariable.h \
		/usr/lib/llvm-10/include/llvm/IR/Instructions.h \
		/usr/lib/llvm-10/include/llvm/Support/AtomicOrdering.h \
		/usr/lib/llvm-10/include/llvm/IR/IntrinsicInst.h \
		/usr/lib/llvm-10/include/llvm/IR/FPEnv.h \
		/usr/lib/llvm-10/include/llvm/IR/Intrinsics.h \
		/usr/lib/llvm-10/include/llvm/IR/IntrinsicEnums.inc \
		/usr/lib/llvm-10/include/llvm/IR/Module.h \
		/usr/lib/llvm-10/include/llvm/IR/Comdat.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalAlias.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalIndirectSymbol.h \
		/usr/lib/llvm-10/include/llvm/IR/GlobalIFunc.h \
		/usr/lib/llvm-10/include/llvm/IR/ProfileSummary.h \
		/usr/lib/llvm-10/include/llvm/Support/CodeGen.h \
		/usr/lib/llvm-10/include/llvm/IR/Operator.h \
		/usr/lib/llvm-10/include/llvm/IR/ValueHandle.h \
		/usr/lib/llvm-10/include/llvm/IR/ConstrainedOps.def \
		/usr/lib/llvm-10/include/llvm/IR/IRPrintingPasses.h \
		/usr/lib/llvm-10/include/llvm/IR/LegacyPassManager.h \
		/usr/lib/llvm-10/include/llvm/Pass.h \
		/usr/lib/llvm-10/include/llvm/PassAnalysisSupport.h \
		/usr/lib/llvm-10/include/llvm/PassSupport.h \
		/usr/lib/llvm-10/include/llvm/PassInfo.h \
		/usr/lib/llvm-10/include/llvm/PassRegistry.h \
		/usr/lib/llvm-10/include/llvm/Support/RWMutex.h \
		/usr/lib/llvm-10/include/llvm/Support/Threading.h \
		/usr/lib/llvm-10/include/llvm/ADT/FunctionExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/Atomic.h \
		/usr/lib/llvm-10/include/llvm/IR/Verifier.h \
		/usr/lib/llvm-10/include/llvm/IR/PassManager.h \
		/usr/lib/llvm-10/include/llvm/ADT/TinyPtrVector.h \
		/usr/lib/llvm-10/include/llvm/IR/PassInstrumentation.h \
		/usr/lib/llvm-10/include/llvm/ADT/Any.h \
		/usr/lib/llvm-10/include/llvm/Support/TypeName.h \
		/usr/lib/llvm-10/include/llvm/IR/PassManagerInternal.h \
		/usr/lib/llvm-10/include/llvm/Support/Debug.h \
		/usr/lib/llvm-10/include/llvm/Support/raw_ostream.h \
		/usr/lib/llvm-10/include/llvm/Support/FileSystem.h \
		/usr/lib/llvm-10/include/llvm/Support/Chrono.h \
		/usr/lib/llvm-10/include/llvm/Support/FormatProviders.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringSwitch.h \
		/usr/lib/llvm-10/include/llvm/Support/FormatVariadicDetails.h \
		/usr/lib/llvm-10/include/llvm/Support/NativeFormatting.h \
		/usr/lib/llvm-10/include/llvm/Support/Error.h \
		/usr/lib/llvm-10/include/llvm-c/Error.h \
		/usr/lib/llvm-10/include/llvm/ADT/StringExtras.h \
		/usr/lib/llvm-10/include/llvm/Support/ErrorOr.h \
		/usr/lib/llvm-10/include/llvm/Support/Format.h \
		/usr/lib/llvm-10/include/llvm/Support/TargetRegistry.h \
		/usr/lib/llvm-10/include/llvm-c/DisassemblerTypes.h \
		/usr/lib/llvm-10/include/llvm/ADT/Triple.h \
		/usr/lib/llvm-10/include/llvm/Support/FormattedStream.h \
		/usr/lib/llvm-10/include/llvm/Support/TargetSelect.h \
		/usr/lib/llvm-10/include/llvm/Config/Targets.def \
		/usr/lib/llvm-10/include/llvm/Config/AsmPrinters.def \
		/usr/lib/llvm-10/include/llvm/Config/AsmParsers.def \
		/usr/lib/llvm-10/include/llvm/Config/Disassemblers.def \
		/usr/lib/llvm-10/include/llvm/Target/TargetMachine.h \
		/usr/lib/llvm-10/include/llvm/Target/TargetOptions.h \
		/usr/lib/llvm-10/include/llvm/MC/MCTargetOptions.h \
		src/utils/symboltable.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/codegencontext.o src/utils/codegencontext.cpp

build/symboltable.o: src/utils/symboltable.cpp src/utils/symboltable.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/symboltable.o src/utils/symboltable.cpp

build/tiger.lexer.o: src/tiger.lexer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/tiger.lexer.o src/tiger.lexer.cpp

build/tiger.parser.o: src/tiger.parser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/tiger.parser.o src/tiger.parser.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

